In [12]:
# Import required libraries
import os
import pandas as pd

In [13]:
# Load the dataset
df = pd.read_csv('../data/train_transcriptomics_2019_UGA.tsv', sep='\t')
df = df.drop(columns=['transcriptomics_id'])
df.head()

    participant_id  timepoint  ensembl_gene_id  raw_count  tpm_count material
0  2019_UGA.ID_208          0  ENSG00000000003        NaN   0.077926  Unknown
1  2019_UGA.ID_208          0  ENSG00000000005        NaN   0.000000  Unknown
2  2019_UGA.ID_208          0  ENSG00000000419        NaN   5.342548  Unknown
3  2019_UGA.ID_208          0  ENSG00000000457        NaN   9.799336  Unknown
4  2019_UGA.ID_208          0  ENSG00000000460        NaN   2.118530  Unknown

In [14]:
# Drop raw_count (entirely NaN) and material (entirely 'Unknown') before pivoting
df = df.drop(columns=['raw_count', 'material'])

df.head()

    participant_id  timepoint  ensembl_gene_id  tpm_count
0  2019_UGA.ID_208          0  ENSG00000000003   0.077926
1  2019_UGA.ID_208          0  ENSG00000000005   0.000000
2  2019_UGA.ID_208          0  ENSG00000000419   5.342548
3  2019_UGA.ID_208          0  ENSG00000000457   9.799336
4  2019_UGA.ID_208          0  ENSG00000000460   2.118530

In [15]:
# Pivot: each row is a (participant_id, timepoint), each gene becomes a column
df_pivot = df.pivot_table(
    index=['participant_id', 'timepoint'],
    columns='ensembl_gene_id',
    values='tpm_count'
)
df_pivot.columns.name = None
df_pivot = df_pivot.reset_index()
print(df_pivot.shape)
df_pivot.head()

(764, 42533)

,participant_id,timepoint,ENSG00000000003,ENSG00000000005,ENSG00000000419,ENSG00000000457,ENSG00000000460,ENSG00000000938,ENSG00000000971,ENSG00000001036,...,ENSG00000284575,ENSG00000284583,ENSG00000284584,ENSG00000284585,ENSG00000284586,ENSG00000284587,ENSG00000284594,ENSG00000284595,ENSG00000284596,ENSG00000284600
0,2019_UGA.ID_001,0,0.149866,0.0,8.066946,8.457258,3.973795,95.386306,0.034801,13.583601,...,NaN,0.0,0.0,NaN,NaN,NaN,0.00000,NaN,NaN,0.000000
1,2019_UGA.ID_001,3,15.000013,0.0,776.000072,588.475583,74.524339,7583.000117,61.000095,417.100782,...,0.0,0.0,0.0,0.0,0.0,0.0,0.99998,0.0,0.0,2.000000
2,2019_UGA.ID_001,7,3.000015,0.0,77.999947,108.812741,33.187328,3000.998877,8.000003,88.023235,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,1.000009
3,2019_UGA.ID_001,28,2.999983,0.0,34.000000,71.397308,3.602668,2090.000385,6.000014,55.109905,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,0.000000
4,2019_UGA.ID_005,0,0.119232,0.0,3.209018,7.973900,2.521538,83.430649,0.110751,10.308613,...,NaN,0.0,0.0,NaN,NaN,NaN,0.00000,NaN,NaN,0.487612

In [17]:
# Save the cleaned dataset to the cleaned_data folder
os.makedirs('../cleaned_data', exist_ok=True)
df_pivot.to_csv('../cleaned_data/transcriptomics_2019_UGA_cleaned.csv', index=False)