In [6]:
# Import required libraries
import os
import pandas as pd

In [7]:
# Load the dataset
df = pd.read_csv('../data/challenge_flow.tsv', sep='\t', low_memory=False)
df = df.drop(columns=['flow_id'])
df.head()

,participant_id,timepoint,parent_population,population_defnition,name,unit,value,material
0,2024_UGA.ID_077,0,CD45plus_cells,CD3-CD14-CD56-CD19+,B cells,percentage,0.073600,Unknown
1,2024_UGA.ID_077,0,CD45plus_cells,CD3+CD14-CD19-,T cells,percentage,0.369000,Unknown
2,2024_UGA.ID_077,0,CD45plus_cells,CD3+CD14-CD19-CD4+CD8-,CD4 T cells,percentage,0.233000,Unknown
3,2024_UGA.ID_077,0,CD45plus_cells,CD3+CD14-CD19-CD4-CD8+,CD8 T cells,percentage,0.115000,Unknown
4,2024_UGA.ID_077,0,CD45plus_cells,CD3+CD14-CD19-CD4-CD8-,DNEG T cells,percentage,0.005129,Unknown

In [8]:
# Rename typo column
df = df.rename(columns={'population_defnition': 'population_definition'})

# Clean material column (standardize labels)
df['material'] = df['material'].replace({
    'specimen type: other': 'Other'
})

# Clean name column (remove trailing '?', strip whitespace)
# Note: do NOT use .str.capitalize() — it corrupts acronyms like "CD4" → "Cd4"
df['name'] = df['name'].str.rstrip('?').str.strip()

df.head()

,participant_id,timepoint,parent_population,population_definition,name,unit,value,material
0,2024_UGA.ID_077,0,CD45plus_cells,CD3-CD14-CD56-CD19+,B cells,percentage,0.073600,Unknown
1,2024_UGA.ID_077,0,CD45plus_cells,CD3+CD14-CD19-,T cells,percentage,0.369000,Unknown
2,2024_UGA.ID_077,0,CD45plus_cells,CD3+CD14-CD19-CD4+CD8-,CD4 T cells,percentage,0.233000,Unknown
3,2024_UGA.ID_077,0,CD45plus_cells,CD3+CD14-CD19-CD4-CD8+,CD8 T cells,percentage,0.115000,Unknown
4,2024_UGA.ID_077,0,CD45plus_cells,CD3+CD14-CD19-CD4-CD8-,DNEG T cells,percentage,0.005129,Unknown

In [9]:
# Print all columns and their unique values
for col in df.columns:
    print(f"{col}: {df[col].unique()}\n")

participant_id: ['2024_UGA.ID_077' '2024_UGA.ID_086' '2024_UGA.ID_128' '2024_UGA.ID_170'
 '2024_UGA.ID_179' '2024_UGA.ID_219' '2024_UGA.ID_215' '2024_UGA.ID_295'
 '2024_UGA.ID_296' '2024_UGA.ID_306' '2024_UGA.ID_335' '2024_UGA.ID_313'
 '2024_UGA.ID_340' '2024_UGA.ID_353' '2024_UGA.ID_411' '2024_UGA.ID_412'
 '2024_UGA.ID_430' '2024_UGA.ID_438' '2024_UGA.ID_443' '2024_UGA.ID_448'
 '2024_UGA.ID_455' '2024_UGA.ID_461' '2024_UGA.ID_512' '2024_UGA.ID_586'
 '2024_UGA.ID_589' '2024_UGA.ID_594' '2024_UGA.ID_600' '2024_UGA.ID_629'
 '2024_UGA.ID_614' '2024_UGA.ID_632' '2024_UGA.ID_649' '2024_UGA.ID_683'
 '2024_UGA.ID_352' '2024_UGA.ID_275' '2024_UGA.ID_321' '2024_UGA.ID_368'
 '2024_UGA.ID_404' '2024_UGA.ID_432' '2024_UGA.ID_572']

timepoint: [0 7]

parent_population: ['CD45plus_cells' 'T_cells' 'CD4_T_cells' 'CD8_T_cells' 'B_cells']

population_definition: ['CD3-CD14-CD56-CD19+' 'CD3+CD14-CD19-' 'CD3+CD14-CD19-CD4+CD8-'
 'CD3+CD14-CD19-CD4-CD8+' 'CD3+CD14-CD19-CD4-CD8-'
 'CD3+CD14-CD19-CD4+CD8+' 'CD3-CD19-CD56+' 'CD3-CD19-CD56hi'
 'CD3-CD19-CD56-HLADR+CD14+CD16-' 'CD3-CD19-CD56-HLADR+CD14+CD16+'
 'CD3-CD19-CD56-HLADR+CD14-CD16+'
 'CD3-CD19-CD56-HLADR+CD14-CD16-CD11c+CD123-'
 'CD3-CD19-CD56-HLADR+CD14-CD16-CD11c-CD123+' 'CD3-CD19-CD56-HLADR-CD123+'
 'CD3-CD19-CD56-HLADR-CD66b+' 'CD3-CD19-CD56-HLADR-CD123-CD66b-' 'CD42b+'
 'CD3+CD14-CD19-CD56+' 'CD3+CD14-CD19-HLADR+CD38+'
 'CD3+CD14-CD19-CD4+CD8-CD45RA+CCR7+' 'CD3+CD14-CD19-CD4+CD8-CD45RA-CCR7-'
 'CD3+CD14-CD19-CD4+CD8-CD45RA-CCR7+' 'CD3+CD14-CD19-CD4+CD8-CD45RA+CCR7-'
 'CD3+CD14-CD19-CD4+CD8-HLADR+CD38+' 'CD3+CD14-CD19-CD4+CD8-CXCR3+'
 'CD3+CD14-CD19-CD4+CD8-CXCR5+' 'CD3+CD14-CD19-CD4-CD8+CD45RA+CCR7+'
 'CD3+CD14-CD19-CD4-CD8+CD45RA-CCR7+' 'CD3+CD14-CD19-CD4-CD8+CD45RA-CCR7-'
 'CD3+CD14-CD19-CD4-CD8+CD45RA+CCR7-' 'CD3+CD14-CD19-CD4-CD8+HLADR+CD38+'
 'CD3-CD14-CD56-CD19+CD20loCD71hiCD27hiCD38hi'
 'CD3-CD14-CD56-CD19+CD20+CD71hi' 'CD3-CD14-CD56-CD19+CD20+CD27-IgD+'
 'CD3-CD14-CD56-CD19+CD20+CD27+IgD-' 'CD3-CD14-CD56-CD19+CD20+CD27+IgD+'
 'CD3-CD14-CD56-CD19+CD20+CD27-IgD-']

name: ['B cells' 'T cells' 'CD4 T cells' 'CD8 T cells' 'DNEG T cells'
 'DPOS T cells' 'CD56+ NK cells' 'CD56hi NK cells' 'Classical monocytes'
 'Intermediate monocytes' 'Non-classical monocytes' 'Conventional DC'
 'Plasmacytoid DCs' 'Basophils' 'Neutrophils' 'Lineage negative'
 'Platelet aggregate CD42b+' 'Cytotoxic CD56+ T cells'
 'Activated CD38+ HLADR+ T cells' 'CD4 T naïve' 'CD4 Tem' 'CD4 Tcm'
 'CD4 Temra' 'Activated CD38+ HLADR+ CD4 T cells' 'Th1 CXCR3+ CD4 T cells'
 'Tfh CXCR5+ CD4 T cell' 'CD8 naïve' 'CD8 Tcm' 'CD8 Tem' 'CD8 Temra'
 'Activated CD38+ HLADR+ CD8 T cells' 'Ab-secreting cells ASC'
 'Activated B cells' 'Naive B cells' 'Memory class switched B cells'
 'Memory nonclass switched B cells' 'Atypical B cells']

unit: ['percentage']

value: [0.0736 0.369  0.233  ... 0.375  0.018  0.188 ]

material: ['Unknown']

In [10]:
# Save the cleaned dataset to the cleaned_data folder
os.makedirs('../cleaned_data', exist_ok=True)
df.to_csv('../cleaned_data/challenge_flow_cleaned.csv', index=False)