## Load cleaned data

hai, participants, transcriptomics (PCA)

In [1]:
import os
from pathlib import Path

import pandas as pd

from data_cleaning.utils import peek

CLEANED_DIR = Path("../cleaned_data")
RAW_DIR = Path("../data")

In [2]:
hai_df = pd.read_csv(CLEANED_DIR / "hai_cleaned.csv", low_memory=False)
print(hai_df.shape)
peek(hai_df)

# Build the reference set of participant IDs — all other tables will be filtered to this
hai_participants = set(hai_df["participant_id"].unique())
print(f"Unique participants in HAI: {len(hai_participants)}")

(3757, 196)
Unique participants in HAI: 3757

In [3]:
participants_df = pd.read_csv(CLEANED_DIR / "participants_cleaned.csv", low_memory=False)
participants_df = participants_df[participants_df["participant_id"].isin(hai_participants)]
print(participants_df.shape)
peek(participants_df)

(3757, 4)

     participant_id PART_biological_sex PART_arm_name  PART_age
0  SDY269.SUB112836              female         Other      28.0
1  SDY269.SUB112849              female         Other      39.0
2  SDY269.SUB112854                male         Other      46.0
3  SDY269.SUB112860              female         Other      32.0
4  SDY269.SUB112881              female         Other      29.0

In [4]:
transcriptomics_df = pd.read_csv(CLEANED_DIR / "transcriptomics_cleaned.csv")
print(transcriptomics_df.shape)
peek(transcriptomics_df)

(395, 291)

,participant_id,TRAN_PC1,TRAN_PC2,TRAN_PC3,TRAN_PC4,TRAN_PC5,TRAN_PC6,TRAN_PC7,TRAN_PC8,TRAN_PC9,TRAN_PC10,TRAN_PC11,TRAN_PC12,TRAN_PC13,TRAN_PC14,TRAN_PC15,TRAN_PC16,TRAN_PC17,TRAN_PC18,TRAN_PC19
0,2019_UGA.ID_001,17.963265,10.116922,0.201273,-17.255525,3.202053,-1.094427,-7.256771,-1.322318,-4.153648,-0.613404,-9.614626,0.720992,4.885530,-4.884685,5.501272,7.561164,-1.978462,-7.722734,-4.200289
1,2019_UGA.ID_005,24.355613,-8.863714,-4.527481,-10.857142,-6.061716,0.245362,-3.501424,-0.653249,9.783679,-0.592398,0.533976,1.964981,-2.689167,0.460776,-1.398064,1.393204,0.935714,6.719536,1.318274
2,2019_UGA.ID_008,4.711335,5.099504,-0.158194,-1.316964,5.371218,-2.394113,-7.784587,1.303140,-0.666468,-0.732497,-7.276848,11.206923,4.566052,1.177469,3.608693,-0.861909,-3.937105,-3.548161,1.860893
3,2019_UGA.ID_011,19.741664,-14.623409,-6.113772,7.795168,-0.831130,5.116629,8.460787,2.478725,1.777897,-0.121422,-0.683163,-0.808980,-1.829761,0.306623,4.709386,-1.172098,2.365919,0.285702,-2.150047
4,2019_UGA.ID_014,26.720715,-15.366108,-2.405799,2.701028,-4.162444,1.662702,-2.216251,1.304555,8.861099,-0.719469,-1.287278,2.894646,-3.274467,1.600970,0.040856,-1.553626,1.243765,1.355677,-0.384338

## Merge

In [5]:
# Start from participants (HAI is the reference set), left join transcriptomics
merged = participants_df.merge(hai_df, on="participant_id", how="left")
merged = merged.merge(transcriptomics_df, on="participant_id", how="left")
print(merged.shape)
peek(merged)

(3757, 489)

,participant_id,PART_biological_sex,PART_arm_name,PART_age,HAI_Anc B/Lee/1940_d0,HAI_Anc B/Lee/1940_d28,HAI_Anc B/Lee/1940_d365,HAI_Anc B/Maryland/1959_d0,HAI_Anc B/Maryland/1959_d28,HAI_Anc B/Singapore/1964_d0,HAI_Anc B/Singapore/1964_d28,HAI_H1N1 A/Beijing/262/1995_d0,HAI_H1N1 A/Beijing/262/1995_d28,HAI_H1N1 A/Beijing/262/1995_d365,HAI_H1N1 A/Brazil/11/1978_d0,HAI_H1N1 A/Brazil/11/1978_d28,HAI_H1N1 A/Brazil/11/1978_d365,HAI_H1N1 A/Brisbane/2/2018_d0,HAI_H1N1 A/Brisbane/2/2018_d28,HAI_H1N1 A/Brisbane/2/2018_d365
0,SDY269.SUB112836,female,Other,28.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,SDY269.SUB112849,female,Other,39.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,SDY269.SUB112854,male,Other,46.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,SDY269.SUB112860,female,Other,32.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,SDY269.SUB112881,female,Other,29.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
os.makedirs('../merged_data', exist_ok=True)
merged.to_csv('merged_data/combined.csv', index=False)
print(f"Saved: {merged.shape}")

Saved: (3757, 489)